insert into `work` (`userId`, `title`, `summary`) values (1, 'Why I Am the Best Jujutsu Sorcerer', 'Summary About Why I Am the Best Jujutsu Sorcerer Fusce ligula lacus, varius gravida nibh sit amet, placerat aliquam lorem. Morbi nec cursus justo. Praesent vitae suscipit nibh. Cras feugiat sit amet velit ac consequat. Proin iaculis vitae ante id interdum. Cras vitae nisl tortor. Praesent in nibh fringilla, elementum lectus ut, sagittis risus.');
insert into `work` (`userId`, `title`, `summary`) values (2, 'Why I Will Always Be Better Than Midoriya', 'Summary About Why I Will Always Be Better Than Midoriya Fusce ligula lacus, varius gravida nibh sit amet, placerat aliquam lorem. Morbi nec cursus justo. Praesent vitae suscipit nibh. Cras feugiat sit amet velit ac consequat. Proin iaculis vitae ante id interdum. Cras vitae nisl tortor. Praesent in nibh fringilla, elementum lectus ut, sagittis risus.');
insert into `work` (`userId`, `title`, `summary`) values (3, 'Why Titans Should Cease to Exist', 'Summary About Why Titans Should Cease to Exist Fusce ligula lacus, varius gravida nibh sit amet, placerat aliquam lorem. Morbi nec cursus justo. Praesent vitae suscipit nibh. Cras feugiat sit amet velit ac consequat. Proin iaculis vitae ante id interdum. Cras vitae nisl tortor. Praesent in nibh fringilla, elementum lectus ut, sagittis risus.');
insert into `work` (`userId`, `title`, `summary`) values (4, 'Why I Secretly Love Kageyama', 'Summary About Why I Secretly Love Kageyama Fusce ligula lacus, varius gravida nibh sit amet, placerat aliquam lorem. Morbi nec cursus justo. Praesent vitae suscipit nibh. Cras feugiat sit amet velit ac consequat. Proin iaculis vitae ante id interdum. Cras vitae nisl tortor. Praesent in nibh fringilla, elementum lectus ut, sagittis risus.');
insert into `work` (`userId`, `title`, `summary`) values (5, 'Why I Secretly Love Tsukki', 'Summary About Why I Secretly Love Tsukki Fusce ligula lacus, varius gravida nibh sit amet, placerat aliquam lorem. Morbi nec cursus justo. Praesent vitae suscipit nibh. Cras feugiat sit amet velit ac consequat. Proin iaculis vitae ante id interdum. Cras vitae nisl tortor. Praesent in nibh fringilla, elementum lectus ut, sagittis risus.');
insert into `work` (`userId`, `title`, `summary`) values (6, 'Why I Will Become the Wizard King', 'Summary About Why I Will Become the Wizard King Fusce ligula lacus, varius gravida nibh sit amet, placerat aliquam lorem. Morbi nec cursus justo. Praesent vitae suscipit nibh. Cras feugiat sit amet velit ac consequat. Proin iaculis vitae ante id interdum. Cras vitae nisl tortor. Praesent in nibh fringilla, elementum lectus ut, sagittis risus.');
insert into `work` (`userId`, `title`, `summary`) values (7, 'Why I Will Perform Impeccably In Nationals', 'Summary About Why I Will Perform Impeccably In Nationals Fusce ligula lacus, varius gravida nibh sit amet, placerat aliquam lorem. Morbi nec cursus justo. Praesent vitae suscipit nibh. Cras feugiat sit amet velit ac consequat. Proin iaculis vitae ante id interdum. Cras vitae nisl tortor. Praesent in nibh fringilla, elementum lectus ut, sagittis risus.');
insert into `work` (`userId`, `title`, `summary`) values (8, 'Why I Think Asta Is Hot', 'Summary About Why I Think Asta Is Hot Fusce ligula lacus, varius gravida nibh sit amet, placerat aliquam lorem. Morbi nec cursus justo. Praesent vitae suscipit nibh. Cras feugiat sit amet velit ac consequat. Proin iaculis vitae ante id interdum. Cras vitae nisl tortor. Praesent in nibh fringilla, elementum lectus ut, sagittis risus.');
insert into `work` (`userId`, `title`, `summary`) values (9, 'Why I Think I Will Become the Wizard King', 'Summary About Why I Think I Will Become the Wizard King Fusce ligula lacus, varius gravida nibh sit amet, placerat aliquam lorem. Morbi nec cursus justo. Praesent vitae suscipit nibh. Cras feugiat sit amet velit ac consequat. Proin iaculis vitae ante id interdum. Cras vitae nisl tortor. Praesent in nibh fringilla, elementum lectus ut, sagittis risus.');
insert into `work` (`userId`, `title`, `summary`) values (10, 'Why I Will Outsmart Karasuno In Our Match', 'Summary About Why I Will Outsmart Karasuno In Our Match Fusce ligula lacus, varius gravida nibh sit amet, placerat aliquam lorem. Morbi nec cursus justo. Praesent vitae suscipit nibh. Cras feugiat sit amet velit ac consequat. Proin iaculis vitae ante id interdum. Cras vitae nisl tortor. Praesent in nibh fringilla, elementum lectus ut, sagittis risus.');



